### ISSUE TITLE
math constants are not recognized by compile method

### ISSUE THREAD

**Issue by MomoDeve** [Angourisoft/MathS#8]
**Description**
trying to compile expression which contains math constants such as **e** and **pi** generates exception because **Compile** method recognizes them as variables:
```cs
System.Collections.Generic.KeyNotFoundException: 'The given key 'e' was not present in the dictionary.'

   at System.ThrowHelper.ThrowKeyNotFoundException[T](T key)
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at AngouriMath.Entity.InnerCompile(FastExpression fe, String[] variables, Dictionary`2 varNamespace) in C:\Users\Momo\source\repos\MathS\AngouriMath\Functions\Evaluation\Compilation\FastExpression.cs:line 106
   at AngouriMath.Entity.InnerCompile(FastExpression fe, String[] variables, Dictionary`2 varNamespace) in C:\Users\Momo\source\repos\MathS\AngouriMath\Functions\Evaluation\Compilation\FastExpression.cs:line 100
   at AngouriMath.Entity.Compile(String[] variables) in C:\Users\Momo\source\repos\MathS\AngouriMath\Functions\Evaluation\Compilation\FastExpression.cs:line 48
   at Samples.Program.Main(String[] _) in C:\Users\Momo\source\repos\MathS\Samples\Samples\Program.cs:line 139
```
(see https://github.com/Angourisoft/MathS/blob/master/AngouriMath/Functions/Evaluation/Compilation/FastExpression.cs#L106)

**To Reproduce**
```cs
static void Main(string[] args)
{
    AngouriMath.Entity expr = "x - pi";
    expr.Compile("x");
}
```
**Conditions**
AngouriMath 1.0.17.2-Beta (latest)
Visual Studio 2019
**Possible solution**
Probably we need to replace such constants with their numeric alternatives if variables with the same names were not passed to the compile method.

**Comment by Angourisoft** [comment]
The problem is solved by now, thank you for contribution
